#
# Makefile for TI's shared transport line discipline
# and its protocol drivers (BT, FM, GPS)
#
obj-$(CONFIG_TI_ST_ACC_330D) 		+= lsm330dlc_acc.o
obj-$(CONFIG_TI_ST_GYRO_330D) 		+= lsm330dlc_gyr.o
obj-$(CONFIG_TAOS_ALS)                          += taos.o
obj-$(CONFIG_TAOS_27723)                        += tmd27723.o
obj-$(CONFIG_SENSORS_AK8963)	+= akm8963.o
